language: generic

sudo: required 
services: 
  - docker

before_install:
  - dockeer build -t atabib/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true atabib/docker-react npm run test -- --coverage